### ISSUE TITLE
正文中无法兼顾对数字加粗和对希腊字母加粗。

### ISSUE THREAD

**Issue by Ptisenbon** [tinoryj/UESTC-Thesis-Latex-Template#10]

**Comment by Ptisenbon** [comment]
加入\usepackage{bm}后 只能加粗数字，但希腊字母没法加粗（只能注释\usepackage{bm}）

**Comment by Ptisenbon** [comment]
用{\bf }进行加粗希腊字母，希腊字母不显示；
注释以后{\bm 希腊字母}仍无法加粗

**Comment by tinoryj** [comment]
不适用bm package并套用加粗，例如：\textbf{12345$\bm{\sigma}$}，可实现加粗目标。
![image](https://user-images.githubusercontent.com/19286867/165456462-570c33d7-261e-4021-bbcc-d069608d34e1.png)
