### ISSUE TITLE
如何保证参考文献中的英文单词不被拆分

### ISSUE THREAD

**Issue by MX0442** [tinoryj/UESTC-Thesis-Latex-Template#11]
![image](https://user-images.githubusercontent.com/104058237/164170630-2369863f-244e-4f0b-8bcc-f71c170427ea.png)
现在编译出来的can参考文献，总是出现自动断行，拆分单词了，学院老师说这样不行，请问这种怎么调整

**Comment by tinoryj** [comment]
若需要确保单词不被断行显示，可在导言区（即main.tex中\begin{document}之前，\documentclass[master]{thesis-uestc}之后）加入以下内容：
\tolerance=1
\emergencystretch=\maxdimen
\hyphenpenalty=10000
\hbadness=10000

**Comment by MX0442** [comment]
谢谢留言，已解决。
