### ISSUE TITLE
目录行间距

### ISSUE THREAD

**Issue by HaibaraMegumi** [tinoryj/UESTC-Thesis-Latex-Template#12]
请问怎么修改目录的行间距为20磅，使用
\setlength\cftbeforechapskip{20pt}
\setlength\cftbeforesecskip{20pt}
\setlength\cftbeforesubsecskip{20pt}
\setlength\cftparskip{1em}
这些命令好像都是在本身间距基础上增加，不是对文字间距baseline增加

**Comment by tinoryj** [comment]
在新版本中已按照规范要求“从中文摘要开始，所有文字段落和标题行间距均取固定值 20磅”将所有行间距设置为20pt。
