### ISSUE TITLE
个人成果分小节列出的时候，小节名怎么修改为如“一、学术论文”，“二、专利”这种格式呢？

### ISSUE THREAD

**Issue by Ptisenbon** [tinoryj/UESTC-Thesis-Latex-Template#13]
现在的用\section是1.1 1.2的分级标题，且标题没有顶格

**Comment by tinoryj** [comment]
将cls文件中的\newenvironment{thesistheaccomplish}处的内容替换为如下内容：
\newenvironment{thesistheaccomplish}{
  \addtocontents{toc}{\protect\setcounter{tocdepth}{0}}
  \renewcommand\thesection{\zhnumber{\arabic{section}}}
  \titleformat{\section}[block]
  {\fontsize{14pt}{14pt}\selectfont\strong}
  {\hspace{-24pt}\bfseries\thesection、}{0pt}{}
  \setcounter{section}{0}
  \nociteaccomplish{*}
  \renewcommand{\bibname}{\thesisaccomplishtitle}
  \begin{thebibliography}{lo}
  \interlinepenalty=10000
  \setlength{\itemsep}{0bp}\setlength{\parskip}{0pt}
  \begin{spacing}{1.667}
  \thispagestyle{fancy}
  \small
}{
  \end{spacing}
  \end{thebibliography}
  \renewcommand{\bibname}{\thesisbibname}
}
![image](https://user-images.githubusercontent.com/19286867/165465557-30427912-9086-4260-ae9f-7aa660b6af52.png)

**Comment by ZhouHuang23** [comment]
新的小节（如：二、xxx） 中的编号会续编上小节（即，一、xxx）中的item。
