### ISSUE TITLE
页码问题：中文摘要的页码没有，罗马数字的页码是从英文摘要开始的

### ISSUE THREAD

**Issue by lucheng2** [tinoryj/UESTC-Thesis-Latex-Template#15]
![image](https://user-images.githubusercontent.com/28623537/168512614-6275ee27-015c-41d8-8287-07ec35f38251.png)

![image](https://user-images.githubusercontent.com/28623537/168512566-409724d7-1256-4bc2-abc3-28e639f473fc.png)

**Comment by tinoryj** [comment]
你是overleaf？还是本地xelate？

**Comment by lucheng2** [comment]
> 

本地xelate，打印的时候阿姨发现的，直接clone编译也是这样。
问题定位应该出在thesis-uestc.cls的434行，我改了之后就正常了。

**Comment by tinoryj** [comment]
好的，可能是xelatex或者相关包不同导致的，测试后会更新一个版本
![image](https://user-images.githubusercontent.com/19286867/168513757-d8375435-5c6a-495a-9f78-0fa728fa912f.png)

**Comment by lucheng2** [comment]
点赞
