### ISSUE TITLE
合作导师设置失败

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#18]
除了promaster找不到，其他都按步骤处理，设置失败

**Comment by tinoryj** [comment]
promaster指将论文模板类型设置为promaster
![image](https://user-images.githubusercontent.com/19286867/171542143-bc44efaa-e2a8-4a1e-a71e-75b24bad3ceb.png)
1118行修改为12bp，书写错误已经更正。

**Comment by tinoryj** [comment]
\documentclass[promaster]{thesis-uestc}
将main.tex中首行设置为如上所示

**Comment by lemywong** [comment]
> promaster指将论文模板类型设置为promaster ![image](https://user-images.githubusercontent.com/19286867/171542143-bc44efaa-e2a8-4a1e-a71e-75b24bad3ceb.png) 1118行修改为12bp，书写错误已经更正。

博士也有副导师 但是好像没有prodoctor的类型？

**Comment by tinoryj** [comment]
已为所有学位类型提供合作导师选项，设置方式参照readme

**Comment by lemywong** [comment]
> 已为所有学位类型提供合作导师选项，设置方式参照readme

合作导师的单位有问题噢

现在是
-- 指导教师
-- 单位
-- 合作导师

如果两位导师都是学校的可能要调整为
-- 指导教师
-- 合作导师
-- 单位

如果不是同一单位的可能要调整为
-- 指导教师
-- 单位
-- 合作导师
-- 单位

**Comment by tinoryj** [comment]
这类型问题请自行修改模板，位置与现有相同
