### ISSUE TITLE
参考文献misc类型无法显示url

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#20]
例如
`@misc{mathworksSolveMixedintegerEngineering,
  title = {Solve a Mixed-Integer Engineering Design Problem Using the Genetic Algorithm},
  author = {MathWorks},
  howpublished = {https://www.mathworks.com/help/gads/solving-a-mixed-integer-engineering-design-problem-using-the-genetic-algorithm.html}
}`

这个key无法正常显示url，不知道是不是因为howpublished这个域不对？查看了bst文件也没看懂

**Comment by hr2894235132** [comment]
> 例如 `@misc{mathworksSolveMixedintegerEngineering, title = {Solve a Mixed-Integer Engineering Design Problem Using the Genetic Algorithm}, author = {MathWorks}, howpublished = {https://www.mathworks.com/help/gads/solving-a-mixed-integer-engineering-design-problem-using-the-genetic-algorithm.html} }`
> 
> 这个key无法正常显示url，不知道是不是因为howpublished这个域不对？查看了bst文件也没看懂

您好，请问您解决了吗？

**Comment by tinoryj** [comment]
链接需要使用\url{}环境包围。和bst没关系
