### ISSUE TITLE
“缩略词表”页面如何只显示缩略词不显示定义的符号？

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#23]
模板默认把\newacronym的缩略词和\newglossaryentry的定义符号全部显示在\thesisglossarylist 页面，请问如何只显示缩略词\newacronym对应的内容，不显示\newglossaryentry的内容？

**Comment by tinoryj** [comment]
https://qa.1r1g.cn/tex/ask/7527551/
参考以上方案试试呢
