### ISSUE TITLE
\tableofcontents 的深度无法修改

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#25]
目前TOC只显示到subsection，如果要显示到subsubsection正常应该用
\setcounter{tocdepth}{4}
但是设置后没效果，不晓得还收什么约束？

**Comment by tinoryj** [comment]
![image](https://user-images.githubusercontent.com/19286867/188640426-d66c5ae2-52ac-42d6-94d7-c4af8ac38fa1.png)
我进行了测试，可以正常显示到subsubsection，仅需要修改\setcounter{tocdepth}{3}；
如果需要将paragraph也添加section counter（但不会在目录中显示），请将\setcounter{tocdepth}上一行的\setcounter{secnumdepth}{3}改为{4}（如下所示）
![image](https://user-images.githubusercontent.com/19286867/188641106-6fe6ada6-c026-4fb5-a56d-483de091ce5d.png)

**Comment by lemywong** [comment]
> ![image](https://user-images.githubusercontent.com/19286867/188640426-d66c5ae2-52ac-42d6-94d7-c4af8ac38fa1.png) 我进行了测试，可以正常显示到subsubsection，仅需要修改\setcounter{tocdepth}{3}； 如果需要将paragraph也添加section counter（但不会在目录中显示），请将\setcounter{tocdepth}上一行的\setcounter{secnumdepth}{3}改为{4}（如下所示） ![image](https://user-images.githubusercontent.com/19286867/188641106-6fe6ada6-c026-4fb5-a56d-483de091ce5d.png)

![image](https://user-images.githubusercontent.com/25263148/188761187-c65ea6b2-8ba5-4736-b618-9bf0847a28b5.png)

我用最新模板也测试了一下 依然显示不到subsubsection 请教下：
1、\setcounter{tocdepth}{3}你加在begin{document}之前？
2、.toc文件删除后重新compile？或者要重新单独编译toc文件（怎么操作？）

**Comment by tinoryj** [comment]
均在cls文件中定义，请直接修改cls

**Comment by lemywong** [comment]
> \setcounter{tocdepth}{3}

clc里修改这一处，没效果
![image](https://user-images.githubusercontent.com/25263148/188766804-63b1928c-1b93-47f8-b4a5-b399df8f1d5e.png)

再加上这一处，也没效果
![image](https://user-images.githubusercontent.com/25263148/188766850-72943b0c-1299-4795-acc7-18de5a90c0db.png)

**Comment by tinoryj** [comment]
![image](https://user-images.githubusercontent.com/19286867/188801011-1559e76c-64d0-4e8d-a118-169a2901c67a.png)
这是我修改的所有内容，仅在cls中进行，编译软件包为Texlive 2022，编译链为xelatex->biblatex->xelatex*2

**Comment by lemywong** [comment]
> ![image](https://user-images.githubusercontent.com/19286867/188801011-1559e76c-64d0-4e8d-a118-169a2901c67a.png) 这是我修改的所有内容，仅在cls中进行，编译软件包为Texlive 2022，编译链为xelatex->biblatex->xelatex*2

升级到Texlive 2022就好了，神奇
