### ISSUE TITLE
成果的标号不正常

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#26]
![image](https://user-images.githubusercontent.com/25263148/188619935-5a5a21d5-9048-4d2f-9936-c41d8605d4a5.png)

居然从4开始的很奇怪，另外按模板这里应该是1.1或1.2之类的，是否可以修改成一、二这样？

**Comment by tinoryj** [comment]
请参照repo中给出的main.tex，标号本身没有问题
![image](https://user-images.githubusercontent.com/19286867/188639242-1308bf3a-275a-498f-9bf7-74c3a1372274.png)

**Comment by tinoryj** [comment]
想改成什么样子的，请直接在cls中查找：
\newenvironment{thesistheaccomplish}{
  \addtocontents{toc}{\protect\setcounter{tocdepth}{0}}
  \renewcommand\thesection{\arabic{section}}
将thesection中的设置进行修改。

**Comment by tinoryj** [comment]
另外，由于成果列表本身使用了chapter，无法实现改为一、二、等的效果（需要chapter）；但可修改为以下格式：
\renewcommand\thesection{\arabic{section}}
%arabic 阿拉伯数字
%roman 小写的罗马数字
%Roman 大写的罗马数字
%alph 小写字母
%Alph 大写字母
