### ISSUE TITLE
阿拉伯数字用\mathbf和\bm都无法加粗

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#27]
不晓得clc里有什么设置限制了数字加粗？如何改回？

**Comment by tinoryj** [comment]
以上两个命令与模板使用的mathspec包冲突，请使用\pmb指令，效果如下所示：
![image](https://user-images.githubusercontent.com/19286867/188643787-ef7be93d-1f66-4b35-94d4-73e762aacb93.png)
