### ISSUE TITLE
中文摘要下似乎没有页码

### ISSUE THREAD

**Issue by gxrevamp** [tinoryj/UESTC-Thesis-Latex-Template#3]
使用最新的模板，罗马数字的页码似乎是从英文摘要开始的，中文摘要没有罗马数字的页码

**Comment by tinoryj** [comment]
更新了一个版本试一下呢？

**Comment by gxrevamp** [comment]
> 

在更新后的thesis-uestc.cls 440行，改为
`\setcounter{page}{1}\setcounter{pseudopage}{1}` 
可以从中文摘要开始计算页码

**Comment by tinoryj** [comment]
新的版本现在对吗？

**Comment by ElvisAo** [comment]
> 

罗马页码还是从英文开始计算的，另外，我按照上面老哥说的进行了修改好像也没用

**Comment by tinoryj** [comment]
我的编译环境是TeX 3.14159265 (TeX Live 2019/Debian)
使用xelatex-bibtex-xelatex*2和Latexmk编译链可正常工作，可否提供一下你们的编译环境和版本信息方面我测试一下呢

**Comment by gxrevamp** [comment]
> 
我用的overleaf，用我上面的方法改了后，格式正确了
谢谢大佬的新模板，真的很方便~
