### ISSUE TITLE
符号解释 & 缩略词 两部分可否单独显示？

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#30]
现在在符号解释里，既有符号也有缩略词解释
在缩略词里，既有缩略词也有符号解释
学位办的老师要求单独显示 但是看了clc文件不晓得改哪个地方 Orz 跪求大神指导

**Comment by tinoryj** [comment]
最新commit已分离，请自行查看main.tex中的示例。注意使用latexmk编译。

**Comment by lemywong** [comment]
> 最新commit的版本已分离，请自行查看main.tex中的示例。注意使用latexmk编译。 或者可直接下载已打包的最新的v1.5版本使用。

万岁万岁！
