### ISSUE TITLE
中文摘要无页码

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#32]
摘要处页码从英文摘要起，中文摘要无页码

![image](https://user-images.githubusercontent.com/25263148/206942362-3bfb0721-63f9-4bea-9c83-e6968152ba8f.png)
![image](https://user-images.githubusercontent.com/25263148/206942381-23bbe07d-30bb-4e13-86c6-5237e473481f.png)

**Comment by tinoryj** [comment]
已修复，请使用最新版本
