### ISSUE TITLE
论文使用授权需要更新

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#33]
按学校发布的10月份模板，论文使用授权最后的括号内容更新了，变成
`（涉密的学位论文须按照国家及学校相关规定管理，在解密后适用于本授权。）`
由于字数变多，更新clc后这一块变成了两页，请问如何更改两个段落之间的距离来保持在一页？？

![image](https://user-images.githubusercontent.com/25263148/206944022-6a9a45d4-d677-413a-9362-384b3ff2b121.png)

**Comment by lemywong** [comment]
修改这一页的行间距就好了
`\begin{spacing}{2.042}`

**Comment by tinoryj** [comment]
已更新，请使用最新版本
