### ISSUE TITLE
中文参考文献超过3人时显示et al

### ISSUE THREAD

**Issue by lemywong** [tinoryj/UESTC-Thesis-Latex-Template#34]
按要求应该是“甲，乙，丙等”，这个怎么改？bst文件没看懂

**Comment by tinoryj** [comment]
已修字符匹配。同时，若中文文献仍不正常，请手动在bib entry中添加language选项，如下图所示：
![image](https://user-images.githubusercontent.com/19286867/207210878-ff2b651b-1416-43b6-9e2a-19e106787b88.png)
