### ISSUE TITLE
一个图中有分图 图目录的显示问题

### ISSUE THREAD

**Issue by ZouTaooo** [tinoryj/UESTC-Thesis-Latex-Template#35]
如果一个图有多个分图，在图题中需要标注主图题和每个子图分图题 但是在图目录中会全部显示 有办法可以只显示主图题吗
![1671247419385](https://user-images.githubusercontent.com/28475389/208221564-a9218051-62d5-4cc9-bf32-77e8c10236c7.png)

**Comment by HeXiaoshu2023** [comment]
> 

你好，这题我会。果不想在图目录中显示分图题，只需要在\caption之后添加一个短标题，这样图目录只显示短标题的内容。
比如，原文字为：\caption{调制高斯脉冲时域与频率波形。(a)调制%高斯脉冲信号的时域波形；(b)调制高斯脉冲信号的频域波形}
你在"{ }"前插入短标题"[ ]"即可：\caption[调制高斯脉冲时域与频率波形]  { 调制高斯脉冲时域与频率波形。(a)调制高斯脉冲信号的时域波形； (b)调制高斯脉冲信号的频域波形}
