### ISSUE TITLE
前面很多页和官方给的还是不同，比如第三页学校给的是A Master Thesis Submitted，该模板是A Master Thesis for Professional Degree Submitted

### ISSUE THREAD

**Issue by xiaomingxige** [tinoryj/UESTC-Thesis-Latex-Template#37]

**Comment by tinoryj** [comment]
可以传一份现在的格式要求上来吗？这个模板主要是根据2022.02.24的格式规范写的，与去年10月的版本可能存在差异。

**Comment by xiaomingxige** [comment]
### 
[电子科技大学研究生学位论文撰写规范_20221017_171527461553.docx](https://github.com/tinoryj/UESTC-Thesis-Latex-Template/files/10416900/_20221017_171527461553.docx)

**Comment by xiaomingxige** [comment]
### 
[电子科技大学研究生学位论文撰写规范_20221017_171527262137.pdf](https://github.com/tinoryj/UESTC-Thesis-Latex-Template/files/10416902/_20221017_171527262137.pdf)

**Comment by tinoryj** [comment]
请问除了例子还有那些位置不同呢？我重新检查之后只看到了这一个地方

**Comment by tinoryj** [comment]
title的问题修好了，如果有其他问题请提出一下

**Comment by xiaomingxige** [comment]
还有首页  专业学位硕士学位论文 与  MASTER THESIS FOR PROFESSIONAL DEGREE间隔太大。
电 子 科 技 大 学  与  UNIVERSITY OF ELECTRONIC SCIENCE AND TECHNOLOGY OF CHINA间隔太大。
电子科技大学图片没有学校的颜色深。
该模板专业学位类别 、学号等与论文题目是对齐的，学校的没有对齐。
等等。挺多不一样的

**Comment by tinoryj** [comment]
先写论文吧，提交的时候封面会由文印中心打印（不允许使用自己的封面），这些问题我会在年后全部修掉。

**Comment by Napoleon940911** [comment]
感谢，期待！

**Comment by ceadmond** [comment]
由tikz绘制的校徽tex文件，可以替换掉封面校徽logo（虽然封面由文印中心统一制作😂）
[logo.zip](https://github.com/tinoryj/UESTC-Thesis-Latex-Template/files/10719011/logo.zip)

**Comment by tinoryj** [comment]
> 由tikz绘制的校徽tex文件，可以替换掉封面校徽logo（虽然封面由文印中心统一制作😂） [logo.zip](https://github.com/tinoryj/UESTC-Thesis-Latex-Template/files/10719011/logo.zip)

收到，谢谢

**Comment by ceadmond** [comment]
应该不能直接替换，校徽尺寸和原来的不一样。

**Comment by tinoryj** [comment]
> 应该不能直接替换，校徽尺寸和原来的不一样。

尺寸我写在模板里的，没有问题，请放心使用

**Comment by Napoleon940911** [comment]
你好，能不能建个QQ群，方便大家即时交流，方便查看聊天记录，以及文件分享等等。


谢谢
祝好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tinoryj/UESTC-Thesis-Latex-Template"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月13日(星期一) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tinoryj/UESTC-Thesis-Latex-Template] 前面很多页和官方给的还是不同，比如第三页学校给的是A Master Thesis Submitted，该模板是A Master Thesis for Professional Degree Submitted (Issue #37)





  
应该不能直接替换，校徽尺寸和原来的不一样。
  
尺寸我写在模板里的，没有问题，请放心使用

**Comment by tinoryj** [comment]
> 你好，能不能建个QQ群，方便大家即时交流，方便查看聊天记录，以及文件分享等等。 谢谢 祝好

建立了一个QQ群（以下群二维码已在README最后添加）
![fd067389d9e008c73074f21784191b6](https://user-images.githubusercontent.com/19286867/218452763-87220d5e-c71b-4c5d-823f-a028f351bfc3.jpg)

**Comment by tinoryj** [comment]
> 还有首页 专业学位硕士学位论文 与 MASTER THESIS FOR PROFESSIONAL DEGREE间隔太大。 电 子 科 技 大 学 与 UNIVERSITY OF ELECTRONIC SCIENCE AND TECHNOLOGY OF CHINA间隔太大。 电子科技大学图片没有学校的颜色深。 该模板专业学位类别 、学号等与论文题目是对齐的，学校的没有对齐。 等等。挺多不一样的

你好，新版本对这些问题进行了修复，尽可能按照学校模板尺寸进行了调整，但由于word中常用的自动对齐等与Latex实现的差别，可能无法实现分毫不差的位置对准。

**Comment by tinoryj** [comment]
Closed since no further updates
