### ISSUE TITLE
子图标题中的文字异常换行

### ISSUE THREAD

**Issue by chicooc** [tinoryj/UESTC-Thesis-Latex-Template#39]
我插入了四个子图，以2x2形式排列，但每个子标题的文字都异常换行了，如"(c) Cap (换行) tion1"。
我已经试过了几种插入子图的命令，子标题文字都会异常换行。
这样不太美观，请问怎么解决。
![截屏2023-02-01 下午6 34 06](https://user-images.githubusercontent.com/28597177/216020135-fd4da60f-584c-4706-bfbe-c8dc134e8eb0.png)

**Comment by tinoryj** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/19286867/216330029-0cb7b028-f161-4fd7-a3ac-735d7a01fb75.png">
请参照上图，使用tabular插入多图是最美观的方式。

**Comment by HeXiaoshu2023** [comment]
好像学校给的模板就是在总图标题上填写信息（标题（a）：xxx；（b）xx 这样子），子图下只有标号。
