### ISSUE TITLE
中文参考文献小于或等于三个作者时出现多余逗号

### ISSUE THREAD

**Issue by WYFyifan** [tinoryj/UESTC-Thesis-Latex-Template#40]
中文参考文献只有三个作者时，第二个作者姓名后面出现一个多余的逗号
![image](https://user-images.githubusercontent.com/19623396/216501253-9e90acde-89c0-48e8-8a43-90da62ce539c.png)
对应的bib文件为：
![image](https://user-images.githubusercontent.com/19623396/216502571-14798bfa-5590-45b5-90ca-cffaee930c74.png)

只有两个作者时，也会出现同样的问题：
![image](https://user-images.githubusercontent.com/19623396/216502654-1939f638-c445-48dd-8257-2a5fb0e341cc.png)
bib文件为：
![image](https://user-images.githubusercontent.com/19623396/216502721-685aa161-c6b3-498f-859d-00d607e4a79c.png)

**Comment by tinoryj** [comment]
![image](https://user-images.githubusercontent.com/19286867/216880158-4b16812b-7d98-4cae-869d-9715ec3bd982.png)
最新版本已修复
