### ISSUE TITLE
参考文献格式等问题

### ISSUE THREAD

**Issue by ceadmond** [tinoryj/UESTC-Thesis-Latex-Template#41]
参照学校格式规范，中文参考文献作者数大于等于3时采用“, 等”结尾，中文参考文献作者数大于等于3时采用“, et al”结尾，更为合适，望采纳。

**Comment by ceadmond** [comment]
好像新版格式规范对图表公式段前段后距离做了修改，例如现在模板里面公式段前段后为8pt(磅)，格式规范里要求的6pt(磅)，应该为
```tex
\AtBeginDocument{
  \setlength{\abovedisplayskip}{6pt}
  \setlength{\belowdisplayskip}{6pt}
  \setlength{\belowdisplayshortskip}{6pt}
  \setlength{\abovedisplayshortskip}{6pt}
}
```

**Comment by tinoryj** [comment]
参考文献格式问题，当前版本符合要求：
![image](https://user-images.githubusercontent.com/19286867/218056428-ad651d5b-ba85-4d83-9d21-ed8037f38158.png)
段前段后距离已经按照您的提示修改，谢谢。
