### ISSUE TITLE
英文封面不会自动删行

### ISSUE THREAD

**Issue by fatandfat** [tinoryj/UESTC-Thesis-Latex-Template#42]
![image](https://user-images.githubusercontent.com/59509491/220302064-722cef41-a472-422b-93f7-b62f1dd064d2.png)
如图在专硕学位类别区域

**Comment by tinoryj** [comment]
因为实现方式为table，无法自动删除，如果你需要，请在cls文件中搜索discipline，随后将以下三行内容进行修改（共有两处），修改前：
![image](https://user-images.githubusercontent.com/19286867/220306764-f499df43-ff57-42bf-851b-1fd816e12551.png)

修改后：
![image](https://user-images.githubusercontent.com/19286867/220306701-be2a25a4-38e0-4be9-9df1-da1a6e5c8dfb.png)
即：multirow中数字改为1，并将之后两行注释。

**Comment by fatandfat** [comment]
感谢回复，但改了还是不管用，用的overleaf，请问这两页是不是文印中心会打印，是的话就这样吧

**Comment by tinoryj** [comment]
> 感谢回复，但改了还是不管用，用的overleaf，请问这两页是不是文印中心会打印，是的话就这样吧

如果是overleaf的可以试一下download之后重新创建project，它的compile比较迷。

**Comment by fatandfat** [comment]
发现原来是有两处discipline，改错地方了，这次搞定了
