### ISSUE TITLE
参考文献引用会议论文时，如何将年后的冒号改为逗号

### ISSUE THREAD

**Issue by YunlianLyu** [tinoryj/UESTC-Thesis-Latex-Template#46]
@inproceedings{abel2016near,
  title={Near optimal behavior via approximate state abstraction},
  author={Abel, David and Hershkowitz, David and Littman, Michael},
  booktitle={International Conference on Machine Learning},
  volume={48},
  pages={2915--2923},
  year={2016},
  organization={PMLR}
}

格式结果：
[https://github.com/YunlianLyu/Temp/blob/main/reference.png](url)

**Comment by tinoryj** [comment]
格式规范为冒号，在格式规范更新前请勿修改。

**Comment by YunlianLyu** [comment]
这是自动回复，已确认收到您的电子邮件。我将尽快处理和回复，谢谢！
(Thank you. Your email is received and will be handled  as soon as possible.)
 
--Yunlian
