### ISSUE TITLE
磅数设置的问题

### ISSUE THREAD

**Issue by ceadmond** [tinoryj/UESTC-Thesis-Latex-Template#47]
学校提供的论文模板是Word模板，在Word中的1 point=1/72inch，在Latex应该采用bp做为磅数单位，而非pt。
可参看中科大论文模板的issue，https://github.com/ustctug/ustcthesis/issues/4。

**Comment by tinoryj** [comment]
Fixed via commit e4af48e16a83a2a206a87f192900d06effb85bfe; Some places kept using pt since I used the official PDF to measure the float numbers of the font size.
