### ISSUE TITLE
document annotation spaces

### ISSUE THREAD

**Issue by prwe98** [tinoryj/UESTC-Thesis-Latex-Template#51]
After the document annotation is inserted, it is identified as mixed Chinese and English by default. Spaces are added on both sides of the document annotation, but there is no space on the format specification in UESTC

**Comment by tinoryj** [comment]
Can you provide an example (Maybe some images to highlight the differences)? I'm a little confused about what "annotation" means.

**Comment by prwe98** [comment]
> Can you provide an example (Maybe some images to highlight the differences)? I'm a little confused about what "annotation" means.

<img width="162" alt="image" src="https://user-images.githubusercontent.com/35358038/223306881-1aa6e669-b7a5-4a0d-9acf-29dbfbe2f1e7.png">
tex's format for annotations is this, with Spaces on both sides

<img width="70" alt="image" src="https://user-images.githubusercontent.com/35358038/223307179-71a9109b-cf0d-48f5-931c-088142bf589e.png">
The format of the notes given by the school is this, with the two sides of the notes next to the Chinese characters

**Comment by tinoryj** [comment]
<img width="162" alt="image" src="https://user-images.githubusercontent.com/19286867/223491834-2e29e60f-da2f-46c0-95c5-ab9ddbe909e0.png">
Fixed by new commit ID a3ca9c29
