### ISSUE TITLE
The issue about reference font

### ISSUE THREAD

**Issue by prwe98** [tinoryj/UESTC-Thesis-Latex-Template#54]
When latex is used to compile chemical expressions in reference, it causes case and subscript errors
<img width="142" alt="image" src="https://user-images.githubusercontent.com/35358038/223641789-7e28807a-9d6f-4e17-839e-ccc098bb8e7b.png">

The title of the paper is:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/35358038/223645595-58c053a6-3106-4d23-ad0b-f57bea5f4226.png">

The compiled operating system is MacOS

**Comment by tinoryj** [comment]
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/19286867/223743028-871d9ba9-12b1-4b1b-ae94-8a2ef36a9a9d.png">
Can you provide your bib? My local test seems no problem with upper and lower corner marks.

**Comment by prwe98** [comment]
`@article{RN89,
	abstract = {Lead-free perovskites CsSnBr3 were predicted to be promising for photovoltaic applications, yet the measured performance is rather disappointing. To understand the mechanism behind the large discrepancy and to further improve the functionality, we study the stability, transition energy levels, and diffusion of different intrinsic defects in pure alpha-CsSnBr3 using density-functional theory calculations. Our results reveal the unique characteristics of the intrinsic defects and their effects on the optoelectronic properties of perovskite CsSnBr3. Among the low formation energy defects, the vacancy defects V-Sn and V-Cs can form shallow energy levels to provide p-type conductivity, while the antisite defects Br-Sn and Br-Cs can act as detrimental recombination centers to deteriorate the performance of devices. Moreover, the mobile defects V-Sn(2-) and V-Cs(-) also degrade device performance by the field-screening effect. The effect of the chemical potential modulation of SnF2 addition into CsSnBr3 is also discussed. These results provide in-depth insights into defect behaviors in the Sn-based perovskites and shed light on related optoelectronic applications.},
	author = {Liang, Y. H. and Cui, X. Y. and Li, F. and Stampfl, C. and Ringer, S. P. and Zheng, R. K.},
	doi = {ARTN 035405 10.1103/PhysRevMaterials.5.035405},
	issn = {2475-9953},
	journal = {Physical Review Materials},
	keywords = {elastic band method charge-transport solar-cells semiconductors substitution efficiency},
	note = {Sk0jm Times Cited:11 Cited References Count:70},
	number = {3},
	title = {First-principles investigation of intrinsic point defects in perovskite $CsSnBr_{3}$},
	type = {Journal Article},
	url = {<Go to ISI>://WOS:000655909600004},
	volume = {5},
	year = {2021},
	bdsk-url-1 = {%3CGo%20to%20ISI%3E://WOS:000655909600004},
	bdsk-url-2 = {https://doi.org/10.1103/PhysRevMaterials.5.035405}}`
Here is the bib. I noticed if it was because of the rule that literature titles are lowercase

**Comment by prwe98** [comment]
> <img alt="image" width="1493" src="https://user-images.githubusercontent.com/19286867/223743028-871d9ba9-12b1-4b1b-ae94-8a2ef36a9a9d.png">
> 
> Can you provide your bib? My local test seems no problem with upper and lower corner marks.

`@article{RN89,
	abstract = {Lead-free perovskites CsSnBr3 were predicted to be promising for photovoltaic applications, yet the measured performance is rather disappointing. To understand the mechanism behind the large discrepancy and to further improve the functionality, we study the stability, transition energy levels, and diffusion of different intrinsic defects in pure alpha-CsSnBr3 using density-functional theory calculations. Our results reveal the unique characteristics of the intrinsic defects and their effects on the optoelectronic properties of perovskite CsSnBr3. Among the low formation energy defects, the vacancy defects V-Sn and V-Cs can form shallow energy levels to provide p-type conductivity, while the antisite defects Br-Sn and Br-Cs can act as detrimental recombination centers to deteriorate the performance of devices. Moreover, the mobile defects V-Sn(2-) and V-Cs(-) also degrade device performance by the field-screening effect. The effect of the chemical potential modulation of SnF2 addition into CsSnBr3 is also discussed. These results provide in-depth insights into defect behaviors in the Sn-based perovskites and shed light on related optoelectronic applications.},
	author = {Liang, Y. H. and Cui, X. Y. and Li, F. and Stampfl, C. and Ringer, S. P. and Zheng, R. K.},
	doi = {ARTN 035405 10.1103/PhysRevMaterials.5.035405},
	issn = {2475-9953},
	journal = {Physical Review Materials},
	keywords = {elastic band method charge-transport solar-cells semiconductors substitution efficiency},
	note = {Sk0jm Times Cited:11 Cited References Count:70},
	number = {3},
	title = {First-principles investigation of intrinsic point defects in perovskite $CsSnBr_{3}$},
	type = {Journal Article},
	url = {<Go to ISI>://WOS:000655909600004},
	volume = {5},
	year = {2021},
	bdsk-url-1 = {%3CGo%20to%20ISI%3E://WOS:000655909600004},
	bdsk-url-2 = {https://doi.org/10.1103/PhysRevMaterials.5.035405}}`
Here is the bib. I noticed if it was because of the rule that literature titles are lowercase.

**Comment by tinoryj** [comment]
Use {} wherever you need to maintain case, for example: {CsSnBr3}.

**Comment by prwe98** [comment]
> Use {} wherever you need to maintain case, for example: {CsSnBr3}.

thx
