### ISSUE TITLE
Failed to complie about \hat{} and \vec{}

### ISSUE THREAD

**Issue by prwe98** [tinoryj/UESTC-Thesis-Latex-Template#55]
Using functions of superscript classes will cause compilation errors. The currently used \hat{} and \vec{} will cause compilation failure, and the log is shown as follows:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/35358038/223716581-bc7d4c63-48fc-4f07-ac95-fcf354027bbb.png">
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/35358038/223716622-d1aedea8-c775-4b99-a0d3-0a658d0ec74f.png">

Failed to compile on either MacOS or Windows

**Comment by tinoryj** [comment]
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/19286867/223741764-780ab46c-e7f7-4e52-a515-013e60e05481.png">
Please update to the newest version and try again. My local test seems no problem.

**Comment by jackylyy** [comment]
\hat不能和\mathcal一起用

**Comment by prwe98** [comment]
> <img alt="image" width="1250" src="https://user-images.githubusercontent.com/19286867/223741764-780ab46c-e7f7-4e52-a515-013e60e05481.png">
> 
> Please update to the newest version and try again. My local test seems no problem.

Conflict because of the use of \usepackage{accents}. Currently solved
