### ISSUE TITLE
What environment is used in this template to draw a three-wire table that can span pages

### ISSUE THREAD

**Issue by prwe98** [tinoryj/UESTC-Thesis-Latex-Template#56]
What environment is used in this template to draw a three-wire table that can span pages

**Comment by tinoryj** [comment]
https://www.tablesgenerator.com/ use this website to generate tables whatever you want.

**Comment by prwe98** [comment]
As the authoring specification shows, how to control font row height in a table, spacing between table topics, spacing between first paragraphs, and so on？Or it's already formed in the latex template.
<img width="792" alt="image" src="https://user-images.githubusercontent.com/35358038/224736419-eb2f5125-76d2-4c4c-8dc6-95a52c6eeef9.png">

**Comment by tinoryj** [comment]
表格格式模板已经定义，不需要手动设定。如果不会写三线表或者其他的跨行等等需求，就用上面的链接生成。
