### ISSUE TITLE
公式编译报错 Use of \reserved@a doesn't match its definition.

### ISSUE THREAD

**Issue by WEIFZH** [tinoryj/UESTC-Thesis-Latex-Template#57]
每一个公式都会出现这个 报错 

Use of \reserved@a doesn't match its definition.

如图，
![image](https://user-images.githubusercontent.com/38351273/224478424-9129a6b2-6147-4825-ac37-b864afa59690.png)

这行就出现上面的错误，请问是什么原因呢？

**Comment by tinoryj** [comment]
You may need to download the full package, there are some fonts in the font folder used in the template.

**Comment by WEIFZH** [comment]
> 

我是直接clone整个项目使用的

**Comment by note286** [comment]
实测TeX Live 2023，Windows 10 无任何问题。

**Comment by tinoryj** [comment]
It was closed for a long time with no response.
