### ISSUE TITLE
subfigure的caption一行只能显示这么长吗

### ISSUE THREAD

**Issue by fatandfat** [tinoryj/UESTC-Thesis-Latex-Template#58]
![image](https://user-images.githubusercontent.com/59509491/224631902-bffb37f5-3e39-4d31-9137-511a760bd7d1.png)
![image](https://user-images.githubusercontent.com/59509491/224631971-d08e4d63-444b-4c42-80d2-515fb7898036.png)

**Comment by note286** [comment]
`.cls`中下面这行写死了宽度，手动移除限制就好了。

```latex
\captionsetup[subfigure]{font=small, belowskip=6pt, width=40pt, justification=centering}
```

**Comment by fatandfat** [comment]
栓q！

**Comment by Nativu5** [comment]
为了提醒后面看到这个 issue 的同学，
根据《电子科技大学学士学位论文撰写格式规范》2.6 部分对插图格式的第 (4) 条规定：

> 有分图时，各分图题按序置于主图题后方，分图题之前用分号”；“隔开

所以本科的同学这里不应该修改模板，而是留空分图题的 /caption，统一在总图题的 /caption 部分填入所有分图的标题。

**Comment by wenli7363** [comment]
> 为了提醒后面看到这个 issue 的同学， 根据《电子科技大学学士学位论文撰写格式规范》2.6 部分对插图格式的第 (4) 条规定：
> 
> > 有分图时，各分图题按序置于主图题后方，分图题之前用分号”；“隔开
> 
> 所以本科的同学这里不应该修改模板，而是留空分图题的 /caption，统一在总图题的 /caption 部分填入所有分图的标题。

请问这里具体怎么写，`\caption{总图题：（a）分图题1；（b）分图题2}`这样吗？看起来怪怪的

**Comment by Nativu5** [comment]
> > 为了提醒后面看到这个 issue 的同学， 根据《电子科技大学学士学位论文撰写格式规范》2.6 部分对插图格式的第 (4) 条规定：
> > > 有分图时，各分图题按序置于主图题后方，分图题之前用分号”；“隔开
> > 
> > 
> > 所以本科的同学这里不应该修改模板，而是留空分图题的 /caption，统一在总图题的 /caption 部分填入所有分图的标题。
> 
> 请问这里具体怎么写，`\caption{总图题：（a）分图题1；（b）分图题2}`这样吗？看起来怪怪的

确实有点怪，但规定如此。格式检查可以通过。
