### ISSUE TITLE
UDC format atfer adding the code for reference

### ISSUE THREAD

**Issue by prwe98** [tinoryj/UESTC-Thesis-Latex-Template#59]
After adding the code
```tex
\tolerance=1
\emergencystretch=\maxdimen
\hyphenpenalty=10000
\hbadness=10000
``` 
the format of UDC changes here.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/35358038/226260703-4b0c85c1-73b3-4e36-8ddd-578c1bbb6651.png">

**Comment by tinoryj** [comment]
You can manually search these contents in the cls file and modify them as you want. I personally recommend stopping using these codes in the tex files.
