### ISSUE TITLE
3 位（100 及以上）参考列表 显示粗糙的悬挂缩进 

### ISSUE THREAD

**Issue by Eldad27** [tinoryj/UESTC-Thesis-Latex-Template#6]
参考列表使用悬挂缩进，并根据研究生办公室证明。 但是，LaTeX 中的当前参考格式似乎使用普通缩进作为参考部分。 我该如何解决这个问题？ 

![Reference problem](https://user-images.githubusercontent.com/37579457/159904087-6a4c4cc3-2115-4ded-8b02-ee8dc4594fb0.PNG)

**Comment by tinoryj** [comment]
目前本模板编译的参考文献格式是正确的悬挂缩进（如下所示）：
![image](https://user-images.githubusercontent.com/19286867/159912453-78b05a09-c2e8-465a-acc7-9098cbe0b26c.png)
参考指南中的参考文献格式：
![image](https://user-images.githubusercontent.com/19286867/159912521-f416855a-8f35-4749-b724-c999ba4eb667.png)
请问可以更清楚地表述问题吗？
您举得例子看上去是正文中通过enumerate等环境产生的枚举结果，与参考文献无关？

**Comment by Eldad27** [comment]
Upon careful thought, I think you are right. The reference format applies the hanging indentation as you just posted. That is correct. However, this is not suppose to be the case according to report from graduate office regarding my pdf submission which is the same as yours. 

I think they confused me. I apologize for the post. I think they confused the enumerated list of referencing guide on the word document on page 22 with the referencing format [Writing Standards_20220321.docx](https://gr.uestc.edu.cn/attached/papers/101/202203/Graduate%20Dissertation(Thesis)%20Writing%20Standards_20220321.docx). 

I will obtain a feedback from them and then close this issue if I'm right.

**Comment by tinoryj** [comment]
you may set \thesisbibliography[large]{reference} in main.tex to fix the problem

**Comment by Eldad27** [comment]
非常感谢。 我很欣赏这个。
