### ISSUE TITLE
中文参考文献年份后应为冒号

### ISSUE THREAD

**Issue by ZZZZZEROTSU** [tinoryj/UESTC-Thesis-Latex-Template#62]
目前模板实际为逗号，求解决方法
![image](https://user-images.githubusercontent.com/39909976/226590153-af6118d6-ab5c-425b-9e28-5f3d5d9d4b09.png)

**Comment by ZZZZZEROTSU** [comment]
可以在bst文件中所有的下述代码段中将```add comma```改为```add colon```
更改前：
```
add comma
format.pages write$
```
更改后：
```
add colon
format.pages write$
```

**Comment by tinoryj** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/19286867/226642299-41c67d8b-1c04-448a-8479-c38def08c707.png">
请不要修改bst模板，仅专著（使用book类型）和学位论文使用逗号，其他均为冒号。例如你给出的例子，标准的正常格式为冒号，请勿修改。
