### ISSUE TITLE
List all authors in Thesis accomplishment section (Research Results Obtained During the Study for Doctoral Degree)

### ISSUE THREAD

**Issue by Eldad27** [tinoryj/UESTC-Thesis-Latex-Template#63]
According to the current format, The original bibliography lists authors up to the third author. The accomplishment section follows this format and list only 3 authors before adding et al. for subsequent authors. However, the requirement is to list all authors in the 'Research Results Obtained During the Study for Doctoral Degree' section. How is this accomplished? How do I fix this by listing all author names in this section? Please help.

**Comment by note286** [comment]
I don't think it would be troublesome for most students to manually list their results.
