### ISSUE TITLE
overleaf采用该模板时，中文摘要下没有页码噢

### ISSUE THREAD

**Issue by yx-orlo** [tinoryj/UESTC-Thesis-Latex-Template#7]

**Comment by tinoryj** [comment]
参照issue3的解决方案试一下呢。由于我没用过overleaf，这个没测试过。

**Comment by yx-orlo** [comment]
issue3的解决方案是针对之前版本的，最新这个版本uestc.cls文件变动了，不能解决呐

**Comment by tinoryj** [comment]
将422行的\setcounter{pseudopage}{0}修改为\setcounter{pseudopage}{1}尝试一下呢

**Comment by yx-orlo** [comment]
不行呢，页码还是从英文摘要开始的

**Comment by tinoryj** [comment]
那把\setcounter{page}{1}\setcounter{pseudopage}{1}加在439和440行之间呢

**Comment by yx-orlo** [comment]
感谢！该方法可行
