### ISSUE TITLE
想问一下怎么根据学校的要求添加主要符号表呢，在网上找了好久都没有

### ISSUE THREAD

**Issue by Ptisenbon** [tinoryj/UESTC-Thesis-Latex-Template#9]
已有的有图目录、表目录和缩略词表

**Comment by tinoryj** [comment]
最新版本已增加主要符号表，使用说明见README，范例见main.tex，但由于目前符号表与缩略词表均使用glossaries宏包实现，暂时无法分离显示(即定义的条目会同时出现在缩略词表和主要符号表中），请选择只使用其中一种。

**Comment by Ptisenbon** [comment]
没想到这么快就回复我了，十分感谢任同学！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yanjing ***@***.***&gt;; 
发送时间: 2022年4月16日(星期六) 下午5:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tinoryj/UESTC-Thesis-Latex-Template] 想问一下怎么根据学校的要求添加主要符号表呢，在网上找了好久都没有 (Issue #9)





 
最新版本已增加主要符号表，使用说明见README，范例见main.tex，但由于目前符号表与缩略词表均使用glossaries宏包实现，暂时无法分离显示(即定义的条目会同时出现在缩略词表和主要符号表中），请选择只使用其中一种。
